# Blockwatch Tezos Indexer for Babylonnet
#
# NOTE: WILL NOT RUN OUT-OF-THE-BOX! YOU NEED TO ADJUST THE SETTINGS
#       BELOW TO YOUR ENVIRONMENT, CREATE DATA DIRECTORIES AND ASSIGN
#       FILESYSTEM PERMISSIONS.
#
version: '2.2'
services:
  # # run tezos node
  # tezos_babylonnet:
  #   image: tezos/tezos:babylonnet
  #   command: ["tezos-node", "run", "--history-mode", "archive"]
  #   ports:
  #     - "9732:9732"
  #   volumes:
  #     - /blockchain_data:/var/run/tezos/node

  # # optional rpc prozy, not required for regular operation
  # tzproxy_babylonnet:
  #   restart: always
  #   image: blockwatch/tzproxy:latest
  #   command: [
  #     "tzproxy",
  #     "-db", "/data/babylonnet/tzproxy/tezos-babylonnet.db",
  #     "-host", "http://tezos_babylonnet:8732",
  #     "-server", "0.0.0.0:8732",
  #     "-blocks-per-cycle", "2048",
  #     "-preserved-cycles", "3",
  #     "run"
  #   ]
  #   volumes:
  #     - index_data:/data

  # tezos index
  tzindex_babylonnet:
    image: blockwatch/tzindex:latest
    volumes:
      - ./tezos:/data
    ports:
      - 8002:8002
    environment:
      - TZ_RPC_HOST=tezos_babylonnet
      # - TZ_RPC_HOST=host.docker.internal
      - TZ_RPC_PORT=8732
      - TZ_SERVER_ADDR=0.0.0.0
      - TZ_SERVER_PORT=8002
      - TZ_SERVER_CORS_ENABLE=true
      - TZ_DATABASE_PATH=/data/babylonnet/tzindex
      - TZ_SNAPSHOT_PATH=/data/snapshots/babylonnet
    stop_grace_period: 1m

  # tzstats frontend
  tzstats_babylonnet:
    image: blockwatch/tzstats:latest
    ports:
      - 8001:8001
    tty: true # fix for Ctrl-C bug in OSX docker-compose
    environment:
      TZSTATS_API_URL: http://localhost:8002
      SV_HEADERS_Content-Security-Policy: default-src 'self' 'unsafe-inline' http://localhost:*;
      SV_SERVER_PORT: 8001
