# Blockwatch Tezos Indexer for Mainnet
#
# NOTE: WILL NOT RUN OUT-OF-THE-BOX! YOU NEED TO ADJUST THE SETTINGS
#       BELOW TO YOUR ENVIRONMENT, CREATE DATA DIRECTORIES AND ASSIGN
#       FILESYSTEM PERMISSIONS.
#
version: '2.2'
volumes:
  mainnet_data:
services:
  # run tezos node
  tezos_mainnet:
    image: tezos/tezos:mainnet
    command: ["tezos-node", "--history-mode", "archive"]
    ports:
      - "9732:9732"
    volumes:
      - mainnet_data:/var/run/tezos/node

  # # optional rpc prozy, not required for regular operation
  # tzproxy_mainnet:
  #   restart: always
  #   image: blockwatch/tzproxy:latest
  #   command: [
  #     "tzproxy",
  #     "-db", "/data/proxy/tezos-mainnet.db",
  #     "-host", "http://tezos_mainnet:8732",
  #     "-server", "0.0.0.0:8732",
  #     "-blocks-per-cycle", "4096",
  #     "-preserved-cycles", "5",
  #     "run"
  #   ]
  #   volumes:
  #     - mainnet_data:/data

  # tezos index
  tzindex_mainnet:
    image: blockwatch/tzindex:latest
    volumes:
      - mainnet_data:/data
    ports:
      - 8002:8002
    environment:
      - TZ_RPC_HOST=tezos_mainnet
      # - TZ_RPC_HOST=host.docker.internal
      - TZ_RPC_PORT=8732
      - TZ_SERVER_ADDR=0.0.0.0
      - TZ_SERVER_PORT=8002
      - TZ_SERVER_CORS_ENABLE=true
      - TZ_DATABASE_PATH=/data/index
      - TZ_SNAPSHOT_PATH=/data/snapshots
    stop_grace_period: 1m

  # tzstats frontend
  tzstats_mainnet:
    image: blockwatch/tzstats:latest
    ports:
      - 8001:8001
    tty: true # fix for Ctrl-C bug in OSX docker-compose
    environment:
      TZSTATS_API_URL: http://localhost:8002
      SV_HEADERS_Content-Security-Policy: default-src 'self' 'unsafe-inline' http://localhost:*;
      SV_SERVER_PORT: 8001
